# Generated by Django 5.1.1 on 2026-08-13 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LigueDesPamplemousseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('Pamplemousse', 'Pamplemousse'), ('Tangerine', 'Tangerine'), ('Clementine', 'Clementine')], max_length=20)),
                ('saison_label', models.CharField(help_text='Ex. 2012-2013', max_length=20)),
                ('annee_debut', models.PositiveIntegerField(help_text='Sert au tri chronologique, ex. 2012')),
            ],
            options={
                'verbose_name': "Année d'archive",
                'verbose_name_plural': "Années d'archive",
                'ordering': ['division', '-annee_debut'],
                'unique_together': {('division', 'saison_label')},
            },
        ),
        migrations.CreateModel(
            name='ArchiveEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('champion_plaza', 'Équipe championne (Plaza)'), ('finaliste_plaza', 'Équipe finaliste (Plaza)'), ('champion_saison', 'Équipe championne de saison')], max_length=20)),
                ('nom_equipe', models.CharField(blank=True, max_length=100)),
                ('cegep', models.CharField(blank=True, max_length=100)),
                ('coach', models.CharField(blank=True, max_length=200)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='LigueDesPamplemousseApp.archiveannee')),
            ],
            options={
                'verbose_name': "Équipe d'archive",
                'verbose_name_plural': "Équipes d'archive",
            },
        ),
        migrations.CreateModel(
            name='ArchiveInterprete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, help_text='Ex. Capitaine, Assistant-capitaine', max_length=30)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretes', to='LigueDesPamplemousseApp.archiveequipe')),
            ],
            options={
                'verbose_name': "Interprète d'archive",
                'verbose_name_plural': "Interprètes d'archive",
                'ordering': ['ordre_affichage', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArchivePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Ex. Recrue de l'année", max_length=150)),
                ('gagnant_nom', models.CharField(blank=True, max_length=200)),
                ('gagnant_equipe', models.CharField(blank=True, help_text='Ex. MIM – Montmorency', max_length=200)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='LigueDesPamplemousseApp.archiveannee')),
            ],
            options={
                'verbose_name': "Prix d'archive",
                'verbose_name_plural': "Prix d'archive",
                'ordering': ['ordre_affichage', 'id'],
            },
        ),
    ]
