# Generated by Django 4.2.13 on 2024-06-10 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CitrusApp', '0002_alter_coach_options_remove_coach_mdp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='equipe_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CitrusApp.equipe'),
        ),
    ]
