# Generated by Django 5.2.6 on 2025-09-27 23:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignements',
            fields=[
                ('id_alignement', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('calendrier_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_calendrier', models.CharField(max_length=50)),
                ('nb_match', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_college', models.CharField(max_length=100, unique=True)),
                ('locationX', models.FloatField()),
                ('locationY', models.FloatField()),
                ('adresse', models.CharField(max_length=255)),
                ('indisponibilites', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('semaine_id', models.AutoField(primary_key=True, serialize=False)),
                ('nb_match', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_equipe', models.CharField(max_length=100, unique=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/')),
                ('division', models.CharField(choices=[('Pamplemousse', 'Pamplemousse'), ('Tangerine', 'Tangerine'), ('Clementine', 'Clementine')], max_length=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('nb_matchVis', models.IntegerField(default=0)),
                ('nb_matchHost', models.IntegerField(default=0)),
                ('indisponibilites', models.JSONField(blank=True, null=True)),
                ('alignements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignements', to='CitrusApp.alignements')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='CitrusApp.college')),
            ],
        ),
        migrations.AddField(
            model_name='alignements',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='CitrusApp.equipe'),
        ),
        migrations.CreateModel(
            name='Interprete',
            fields=[
                ('interprete_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_interprete', models.CharField(max_length=100)),
                ('pronom_interprete', models.CharField(blank=True, default='', max_length=20)),
                ('numero_interprete', models.CharField(blank=True, default='', max_length=20)),
                ('role_interprete', models.CharField(blank=True, max_length=1, null=True)),
                ('alignement', models.ManyToManyField(related_name='interpretes', to='CitrusApp.alignements')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('score_eq1', models.IntegerField(default=0)),
                ('score_eq2', models.IntegerField(default=0)),
                ('etoile1', models.CharField(blank=True, max_length=255, null=True)),
                ('etoile2', models.CharField(blank=True, max_length=255, null=True)),
                ('etoile3', models.CharField(blank=True, max_length=255, null=True)),
                ('etoile4', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_arbitre', models.CharField(blank=True, max_length=100, null=True)),
                ('date_match', models.DateTimeField(blank=True, null=True)),
                ('url_photo', models.URLField(blank=True, null=True)),
                ('division', models.CharField(choices=[('Pamplemousse', 'Pamplemousse'), ('Tangerine', 'Tangerine'), ('Clementine', 'Clementine')], default='Pamplemousse', max_length=50)),
                ('completed_flag', models.BooleanField(default=False)),
                ('validated_flag', models.BooleanField(default=False)),
                ('improvisations', models.JSONField(blank=True, default=list, null=True)),
                ('cache', models.JSONField(blank=True, default=dict, null=True)),
                ('equipe1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_hote', to='CitrusApp.equipe')),
                ('equipe2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_visiteure', to='CitrusApp.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='matchs',
            field=models.ManyToManyField(blank=True, null=True, to='CitrusApp.match'),
        ),
        migrations.CreateModel(
            name='Punition',
            fields=[
                ('punition_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_punition', models.CharField(max_length=50)),
                ('est_majeure', models.BooleanField(default=False)),
                ('equipe_punie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipe_punie', to='CitrusApp.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='punitions',
            field=models.ManyToManyField(blank=True, null=True, related_name='punitions', to='CitrusApp.punition'),
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('saison_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_saison', models.CharField(max_length=255)),
                ('est_active', models.BooleanField(default=False)),
                ('calendrier_officiel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CitrusApp.calendrier')),
            ],
        ),
        migrations.AddField(
            model_name='calendrier',
            name='saison_officiel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CitrusApp.saison'),
        ),
        migrations.AddField(
            model_name='alignements',
            name='saison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saison', to='CitrusApp.saison'),
        ),
        migrations.AddField(
            model_name='match',
            name='semaine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs', to='CitrusApp.semaine'),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('serie_id', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(choices=[('Pamplemousse', 'Pamplemousse'), ('Tangerine', 'Tangerine'), ('Clementine', 'Clementine')], max_length=50)),
                ('saison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CitrusApp.saison')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CitrusApp.serie'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_session', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Automne', 'Automne'), ('Hiver', 'Hiver')], max_length=25)),
                ('nb_semaine', models.IntegerField(default=10)),
                ('calendrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='CitrusApp.calendrier')),
                ('saison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CitrusApp.saison')),
            ],
        ),
        migrations.AddField(
            model_name='semaine',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semaines', to='CitrusApp.session'),
        ),
        migrations.AddField(
            model_name='match',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CitrusApp.session'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('coach_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_coach', models.CharField(max_length=100)),
                ('prenom_coach', models.CharField(max_length=100)),
                ('pronom_coach', models.CharField(blank=True, max_length=20, null=True)),
                ('courriel', models.EmailField(max_length=255, unique=True)),
                ('admin_flag', models.BooleanField(default=False)),
                ('validated_flag', models.BooleanField(default=False)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college', to='CitrusApp.college')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CitrusApp.equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
