# Generated by Django 5.1.1 on 2025-10-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CitrusApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendrier',
            name='saison_officiel',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='nb_matchHost',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='nb_matchVis',
        ),
    ]
