# Generated by Django 5.1.1 on 2025-10-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CitrusApp', '0002_remove_calendrier_saison_officiel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interprete',
            name='numero_interprete',
        ),
        migrations.RemoveField(
            model_name='interprete',
            name='role_interprete',
        ),
    ]
