# Generated by Django 5.1.1 on 2025-10-21 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitrusApp', '0003_remove_interprete_numero_interprete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignement',
            name='coach_id',
        ),
        migrations.AddField(
            model_name='alignement',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach', to=settings.AUTH_USER_MODEL),
        ),
    ]
