# Generated by Django 5.1.1 on 2025-10-28 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitrusApp', '0004_remove_alignement_coach_id_alignement_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='saison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saison_match', to='CitrusApp.saison'),
        ),
        migrations.AlterField(
            model_name='alignement',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignements', to=settings.AUTH_USER_MODEL),
        ),
    ]
