# Generated by Django 5.1.1 on 2026-05-04 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitrusApp', '0005_match_saison_alter_alignement_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='alignement',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='matchs',
        ),
        migrations.AlterField(
            model_name='match',
            name='punitions',
            field=models.ManyToManyField(blank=True, related_name='punitions', to='CitrusApp.punition'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='RequeteReportMatch',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nouvelle_date', models.DateField()),
                        ('coach1_validation', models.BooleanField(default=False)),
                        ('coach2_validation', models.BooleanField(default=False)),
                        ('admin_validation', models.BooleanField(default=False)),
                        ('date_creation', models.DateTimeField(auto_now_add=True)),
                        ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                        ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=10)),
                        ('coach_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requetes_report_comme_coach1', to=settings.AUTH_USER_MODEL)),
                        ('coach_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requetes_report_comme_coach2', to=settings.AUTH_USER_MODEL)),
                        ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cree_par', to=settings.AUTH_USER_MODEL)),
                        ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requete_report_match', to='CitrusApp.match')),
                    ],
                ),
            ],
        ),
    ]
