# Generated by Django 5.1.1 on 2026-09-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitrusApp', '0009_remove_alignement_coach_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignement',
            name='division',
            field=models.CharField(blank=True, choices=[('Pamplemousse', 'Pamplemousse'), ('Tangerine', 'Tangerine'), ('Clementine', 'Clementine')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alignement',
            name='est_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='alignement',
            unique_together={('equipe', 'saison')},
        ),
    ]
